/* IndoSpotters frontend. Browser-safe Supabase publishable key only; never add a secret/service-role key here. */
const SUPABASE_URL = "https://evriubsmhbeukkfqfqvq.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_p-k3v3Fcp2D52PM552cX-w_NX2jmjYI";
const DEMO_AIRPORTS = [
 {icao:"WIII",name:"Soekarno-Hatta International Airport",city:"Tangerang / Jakarta",region:"Banten"},
 {icao:"WARR",name:"Juanda International Airport",city:"Surabaya",region:"East Java"},
 {icao:"WIMM",name:"Kualanamu International Airport",city:"Medan",region:"North Sumatra"},
 {icao:"WIBB",name:"Sultan Syarif Kasim II International Airport",city:"Pekanbaru",region:"Riau"},
 {icao:"WADD",name:"I Gusti Ngurah Rai International Airport",city:"Denpasar",region:"Bali"},
 {icao:"WICC",name:"Husein Sastranegara International Airport",city:"Bandung",region:"West Java"},
 {icao:"WIKK",name:"Halim Perdanakusuma International Airport",city:"Jakarta",region:"Jakarta"},
 {icao:"WALL",name:"Sultan Aji Muhammad Sulaiman Sepinggan International Airport",city:"Balikpapan",region:"East Kalimantan"},
 {icao:"WAHH",name:"Yogyakarta International Airport",city:"Kulon Progo",region:"Yogyakarta"},
 {icao:"WAMM",name:"Sam Ratulangi International Airport",city:"Manado",region:"North Sulawesi"},
 {icao:"WAAA",name:"Sultan Hasanuddin International Airport",city:"Makassar",region:"South Sulawesi"},
 {icao:"WIOO",name:"Supadio International Airport",city:"Pontianak",region:"West Kalimantan"}
];
const DEMO_TYPES = [
 ["A320","Airbus","A320","Commercial"],["A20N","Airbus","A320neo","Commercial"],["A321","Airbus","A321","Commercial"],["A21N","Airbus","A321neo","Commercial"],
 ["A332","Airbus","A330-200","Commercial"],["A333","Airbus","A330-300","Commercial"],["A339","Airbus","A330-900neo","Commercial"],["A359","Airbus","A350-900","Commercial"],
 ["B738","Boeing","737-800","Commercial"],["B739","Boeing","737-900ER","Commercial"],["B38M","Boeing","737 MAX 8","Commercial"],["B39M","Boeing","737 MAX 9","Commercial"],
 ["B744","Boeing","747-400","Commercial/Cargo"],["B748","Boeing","747-8","Commercial/Cargo"],["B772","Boeing","777-200","Commercial"],["B77W","Boeing","777-300ER","Commercial"],
 ["B788","Boeing","787-8 Dreamliner","Commercial"],["B789","Boeing","787-9 Dreamliner","Commercial"],["AT72","ATR","ATR 72","Regional"],["AT43","ATR","ATR 42","Regional"],
 ["DH8D","De Havilland Canada","Dash 8 Q400","Regional"],["C208","Cessna","208 Caravan","General aviation"],["CN35","CASA","CN-235","Military/Transport"],
 ["C130","Lockheed Martin","C-130 Hercules","Military/Transport"],["A400","Airbus Defence","A400M Atlas","Military/Transport"],["RFL1","Dassault Aviation","Rafale","Military"],
 ["F16","Lockheed Martin","F-16 Fighting Falcon","Military"],["FA50","KAI","FA-50 Fighting Eagle","Military"],["H145","Airbus Helicopters","H145","Helicopter"],["AW139","Leonardo","AW139","Helicopter"],
 ["B77L","Boeing","777 Freighter","Cargo"],["MD11","McDonnell Douglas","MD-11","Cargo"]
].map(([type_code,manufacturer,model,category])=>({type_code,manufacturer,model,category}));
let supabase=null,currentUser=null,airports=DEMO_AIRPORTS,allPhotos=[],aircraftTypes=DEMO_TYPES,registryEntries=[],authMode="signin";
const $=id=>document.getElementById(id);
const isConfigured=()=>SUPABASE_URL.startsWith("https://")&&!SUPABASE_URL.includes("YOUR_")&&SUPABASE_ANON_KEY&&!SUPABASE_ANON_KEY.includes("YOUR_");
function toast(m){const e=$("toast");if(!e)return;e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),3200)}
function escapeHtml(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function formatDate(v){if(!v)return "Date not supplied";const d=new Date(v+"T00:00:00");return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}
function init(){renderAirports();renderAircraftTypes();if(!isConfigured()){allPhotos=[];renderPhotos([]);return}supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);loadData();loadAircraftCatalog();supabase.auth.getSession().then(({data})=>{currentUser=data.session?.user||null;updateAuthUI()});supabase.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;updateAuthUI()})}
async function loadData(){const [{data:ad,error:ae},{data:pd,error:pe}]=await Promise.all([supabase.from("airports").select("*").order("icao"),supabase.from("photos").select("id,registration,airline,aircraft_type,airport_code,caption,photographer_name,photo_date,livery,storage_path,created_at").eq("status","approved").order("created_at",{ascending:false}).limit(150)]);if(!ae&&ad?.length)airports=ad;renderAirports();if(pe){console.error(pe);allPhotos=[]}else{allPhotos=await Promise.all((pd||[]).map(async p=>{if(!p.storage_path)return {...p,image_url:""};const {data,error}=await supabase.storage.from("aircraft-photos").createSignedUrl(p.storage_path,3600);if(error)console.warn(error.message);return {...p,image_url:data?.signedUrl||""}}))}renderPhotos(allPhotos);$("photo-count").textContent=allPhotos.length;$("airport-count").textContent=airports.length}
function renderAirports(){if($("airport-grid"))$("airport-grid").innerHTML=airports.map(a=>`<article class="airport-card"><div class="airport-code">${escapeHtml(a.icao)}</div><div class="airport-name">${escapeHtml(a.name)}</div><div class="airport-city">${escapeHtml(a.city||"Indonesia")}</div><div class="airport-region">${escapeHtml(a.region||"Indonesia")}</div></article>`).join("");const opts=airports.map(a=>`<option value="${escapeHtml(a.icao)}">${escapeHtml(a.icao)} — ${escapeHtml(a.name)}</option>`).join("");if($("airport-filter"))$("airport-filter").innerHTML='<option value="">All airports</option>'+opts;if($("upload-airport"))$("upload-airport").innerHTML='<option value="">Select airport</option>'+opts}
function photoCard(p){const img=p.image_url?`<img loading="lazy" src="${escapeHtml(p.image_url)}" alt="${escapeHtml(p.registration+" "+p.aircraft_type)}">`:`<div class="placeholder-plane">✈</div>`;return `<article class="photo-card" tabindex="0" role="button" data-photo-id="${escapeHtml(p.id||p.registration)}"><div class="photo-thumb">${img}<span class="photo-tag">${escapeHtml(p.airport_code||"INDONESIA")}</span></div><div class="photo-info"><div class="photo-reg">${escapeHtml(p.registration||"Unknown registration")}</div><div class="photo-type">${escapeHtml(p.aircraft_type||"Aircraft type not supplied")}</div><div class="photo-meta"><span class="photo-airline">${escapeHtml(p.airline||"Unknown operator")}</span><span>${escapeHtml(formatDate(p.photo_date))}</span></div></div></article>`}
function renderPhotos(ps){if($("result-count"))$("result-count").textContent=`${ps.length} ${ps.length===1?"photo":"photos"}`;if($("gallery-grid"))$("gallery-grid").innerHTML=ps.length?ps.map(photoCard).join(""):'<div class="empty-state">No approved photos match this search yet. Be the first to submit one.</div>'}
function searchPhotos(e){e?.preventDefault();const q=$("q").value.trim().toLowerCase(),a=$("airport-filter").value,s=$("sort-filter").value;let f=allPhotos.filter(p=>[p.registration,p.airline,p.aircraft_type,p.airport_code,p.livery,p.photographer_name].some(v=>String(v||"").toLowerCase().includes(q))&&(!a||p.airport_code===a));if(s==="oldest")f.sort((x,y)=>String(x.photo_date||"").localeCompare(String(y.photo_date||"")));else if(s==="registration")f.sort((x,y)=>String(x.registration||"").localeCompare(String(y.registration||"")));else f.sort((x,y)=>String(y.created_at||y.photo_date||"").localeCompare(String(x.created_at||x.photo_date||"")));renderPhotos(f)}
function updateAuthUI(){if($("auth-button"))$("auth-button").textContent=currentUser?(currentUser.user_metadata?.display_name||currentUser.email?.split("@")[0]||"Account")+" · Sign out":"Sign in";$("account-panel")?.classList.toggle("hidden",!currentUser);if($("upload-status"))$("upload-status").textContent=currentUser?"Signed in. Your uploads will be sent for review.":"Sign in to submit a photo.";if(currentUser){loadSubmissions();loadProfile()}}
async function handleAuthButton(){if(!supabase){toast("Supabase is not configured.");return}if(currentUser){const {error}=await supabase.auth.signOut();if(error)toast(error.message);else toast("Signed out.")}else $("auth-dialog").showModal()}
async function handleAuth(e){e.preventDefault();if(!supabase)return;const email=$("auth-email").value.trim(),password=$("auth-password").value,name=$("auth-display-name").value.trim();$("auth-status").textContent="Please wait…";const result=authMode==="signup"?await supabase.auth.signUp({email,password,options:{data:{display_name:name||email.split("@")[0]}}}):await supabase.auth.signInWithPassword({email,password});if(result.error){$("auth-status").textContent=result.error.message;return}$("auth-status").textContent=authMode==="signup"?"Account created. Check your email if confirmation is enabled.":"Signed in successfully.";if(authMode==="signin")setTimeout(()=>$("auth-dialog").close(),700)}
function toggleAuthMode(){authMode=authMode==="signin"?"signup":"signin";$("auth-title").textContent=authMode==="signup"?"Create account":"Sign in";$("auth-submit").textContent=authMode==="signup"?"Create account":"Sign in";$("auth-toggle").textContent=authMode==="signup"?"Already have an account? Sign in":"Need an account? Sign up";$("auth-password").autocomplete=authMode==="signup"?"new-password":"current-password";$("signup-name-wrap")?.classList.toggle("hidden",authMode!=="signup");$("auth-display-name").required=authMode==="signup"}
async function loadProfile(){if(!currentUser||!supabase)return;$("profile-email").textContent=currentUser.email||"";const {data,error}=await supabase.from("profiles").select("display_name").eq("id",currentUser.id).maybeSingle();if(error){console.warn(error.message);$("profile-display-name").value=currentUser.user_metadata?.display_name||currentUser.email?.split("@")[0]||"";return}$("profile-display-name").value=data?.display_name||currentUser.user_metadata?.display_name||currentUser.email?.split("@")[0]||""}
async function saveProfile(e){e.preventDefault();if(!currentUser)return;const name=$("profile-display-name").value.trim();if(!name){$("profile-status").textContent="Please enter a display name.";return}$("profile-status").textContent="Saving…";const {error}=await supabase.from("profiles").upsert({id:currentUser.id,display_name:name,role:"spotter"},{onConflict:"id"});if(error){$("profile-status").textContent="Could not save profile: "+error.message;return}const {error:authError}=await supabase.auth.updateUser({data:{display_name:name}});if(authError)console.warn(authError.message);$("profile-status").textContent="Profile saved.";updateAuthUI();toast("Profile updated")}
async function submitPhoto(e){e.preventDefault();if(!supabase){$("upload-status").textContent="Supabase is not configured.";return}if(!currentUser){$("auth-dialog").showModal();$("upload-status").textContent="Please sign in before submitting.";return}const file=$("photo-file").files[0];if(!file)return;if(file.size>12*1024*1024){$("upload-status").textContent="Please choose an image smaller than 12 MB.";return}if(!["image/jpeg","image/png","image/webp"].includes(file.type)){$("upload-status").textContent="Use a JPG, PNG, or WebP image.";return}const status=$("upload-status");status.textContent="Uploading photo…";const ext=file.name.split(".").pop().toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",path=`${currentUser.id}/${crypto.randomUUID()}.${ext}`;const {error:se}=await supabase.storage.from("aircraft-photos").upload(path,file,{contentType:file.type,upsert:false});if(se){status.textContent="Upload failed: "+se.message;return}const {error:de}=await supabase.from("photos").insert({user_id:currentUser.id,registration:$("registration").value.trim().toUpperCase(),airline:$("airline").value.trim(),aircraft_type:$("aircraft-type").value.trim(),airport_code:$("upload-airport").value,photo_date:$("photo-date").value||null,livery:$("livery").value.trim()||null,caption:$("caption").value.trim()||null,image_url:"",storage_path:path,status:"pending",photographer_name:$("profile-display-name")?.value.trim()||currentUser.user_metadata?.display_name||currentUser.email?.split("@")[0]||"Community spotter"});if(de){status.textContent="Photo uploaded, but details could not be saved: "+de.message;return}status.textContent="Submitted! Your photo is waiting for moderator approval.";$("upload-form").reset();loadSubmissions();toast("Photo submitted for review")}
async function loadSubmissions(){if(!currentUser||!supabase)return;const {data,error}=await supabase.from("photos").select("id,registration,aircraft_type,airport_code,status,created_at").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(50);if(error){$("my-submissions").innerHTML=`<p class="muted small">Could not load submissions: ${escapeHtml(error.message)}</p>`;return}$("my-submissions").innerHTML=(data||[]).length?(data||[]).map(p=>`<div class="submission-item"><span><strong>${escapeHtml(p.registration)}</strong> · ${escapeHtml(p.aircraft_type)} · ${escapeHtml(p.airport_code)}</span><span class="status-pill ${escapeHtml(p.status)}">${escapeHtml(p.status)}</span></div>`).join(""):'<p class="muted small">You have not submitted any photos yet.</p>'}
async function loadAircraftCatalog(){const [{data:td,error:te},{data:rd,error:re}]=await Promise.all([supabase.from("aircraft_types").select("type_code,manufacturer,model,category").order("manufacturer").order("model"),supabase.from("aircraft_registry").select("registration,operator,type_code,serial_number,notes,status,created_at").eq("status","approved").order("registration").limit(500)]);if(!te&&td?.length)aircraftTypes=td;if(!re)registryEntries=rd||[];renderAircraftTypes();renderRegistry();}
function renderAircraftTypes(){const q=($("type-search")?.value||"").trim().toLowerCase();const filtered=aircraftTypes.filter(t=>[t.type_code,t.manufacturer,t.model,t.category].some(v=>String(v||"").toLowerCase().includes(q)));if($("aircraft-type-count"))$("aircraft-type-count").textContent=`${aircraftTypes.length} aircraft types`;if($("aircraft-type-grid"))$("aircraft-type-grid").innerHTML=filtered.map(t=>`<article class="type-card"><span class="type-code">${escapeHtml(t.type_code)}</span><strong>${escapeHtml(t.model)}</strong><span>${escapeHtml(t.manufacturer)} · ${escapeHtml(t.category)}</span></article>`).join("")||'<p class="muted small">No aircraft types match this filter.</p>';if($("registry-type"))$("registry-type").innerHTML='<option value="">Select aircraft type</option>'+aircraftTypes.map(t=>`<option value="${escapeHtml(t.type_code)}">${escapeHtml(t.manufacturer)} ${escapeHtml(t.model)} (${escapeHtml(t.type_code)})</option>`).join("")}
function renderRegistry(){const q=($("registry-search")?.value||"").trim().toLowerCase();const filtered=registryEntries.filter(r=>[r.registration,r.operator,r.type_code,r.serial_number].some(v=>String(v||"").toLowerCase().includes(q)));if($("registry-results"))$("registry-results").innerHTML=filtered.length?filtered.map(r=>{const t=aircraftTypes.find(x=>x.type_code===r.type_code);return `<article class="registry-row"><div><strong>${escapeHtml(r.registration)}</strong><p>${escapeHtml(r.operator||"Operator not listed")} · ${escapeHtml(t?`${t.manufacturer} ${t.model}`:r.type_code||"Type not listed")}</p>${r.serial_number?`<small>MSN ${escapeHtml(r.serial_number)}</small>`:""}</div><span class="verified-tag">Approved entry</span></article>`}).join(""):'<div class="empty-state">No approved aircraft registrations found yet. Sign in to suggest an entry.</div>'}
async function submitRegistry(e){e.preventDefault();if(!currentUser){$("registry-status").textContent="Sign in to suggest an aircraft registration.";$("auth-dialog").showModal();return}const registration=$("registry-registration").value.trim().toUpperCase();if(!/^[A-Z0-9-]{3,16}$/.test(registration)){$("registry-status").textContent="Use 3–16 letters, numbers, or hyphens for the registration.";return}$("registry-status").textContent="Submitting…";const {error}=await supabase.from("aircraft_registry").insert({registration,operator:$("registry-operator").value.trim()||null,type_code:$("registry-type").value,serial_number:$("registry-serial").value.trim()||null,notes:$("registry-notes").value.trim()||null,status:"pending",submitted_by:currentUser.id});if(error){$("registry-status").textContent=error.code==="23505"?"That registration already exists or is awaiting review.":"Could not submit: "+error.message;return}$("registry-status").textContent="Registration suggestion sent for moderator review.";$("registry-form").reset();toast("Registration sent for review")}
function openPhoto(id){const p=allPhotos.find(x=>String(x.id||x.registration)===String(id));if(!p)return;$("photo-detail").innerHTML=`${p.image_url?`<img src="${escapeHtml(p.image_url)}" alt="${escapeHtml(p.registration)}">`:""}<div class="detail-text"><p class="eyebrow">${escapeHtml(p.airport_code||"INDONESIA")} · ${escapeHtml(formatDate(p.photo_date))}</p><h2>${escapeHtml(p.registration||"Unknown registration")}</h2><p><strong>${escapeHtml(p.airline||"Unknown operator")}</strong> · ${escapeHtml(p.aircraft_type||"Aircraft type not supplied")}</p>${p.livery?`<p>Livery: ${escapeHtml(p.livery)}</p>`:""}${p.caption?`<p>${escapeHtml(p.caption)}</p>`:""}<p>Photographer: <strong>${escapeHtml(p.photographer_name||"Community spotter")}</strong></p></div>`;$("photo-dialog").showModal()}
document.addEventListener("DOMContentLoaded",()=>{init();$("search-form").addEventListener("submit",searchPhotos);$("q").addEventListener("input",searchPhotos);$("airport-filter").addEventListener("change",searchPhotos);$("sort-filter").addEventListener("change",searchPhotos);$("auth-button").addEventListener("click",handleAuthButton);$("auth-form").addEventListener("submit",handleAuth);$("auth-toggle").addEventListener("click",toggleAuthMode);$("close-auth").addEventListener("click",()=>$ ("auth-dialog").close());$("upload-form").addEventListener("submit",submitPhoto);$("refresh-submissions").addEventListener("click",loadSubmissions);$("profile-form").addEventListener("submit",saveProfile);$("registry-form").addEventListener("submit",submitRegistry);$("registry-search").addEventListener("input",renderRegistry);$("type-search").addEventListener("input",renderAircraftTypes);$("close-photo").addEventListener("click",()=>$ ("photo-dialog").close());$("gallery-grid").addEventListener("click",e=>{const card=e.target.closest("[data-photo-id]");if(card)openPhoto(card.dataset.photoId)});$("gallery-grid").addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.matches("[data-photo-id]")){e.preventDefault();openPhoto(e.target.dataset.photoId)}})});
