/* IndoSpotters — connected Supabase frontend. Never place a service-role key here. */
const SUPABASE_URL = "https://evriubsmhbeukkfqfqvq.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_p-k3v3Fcp2D52PM552cX-w_NX2jmjYI";
let supabase, currentUser = null, airports = [], allPhotos = [], aircraftTypes = [], aircraftRegistry = [], authMode = "signin";
const $ = id => document.getElementById(id);
const escapeHtml = (v="") => String(v).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const formatDate = value => { if(!value) return "Date not supplied"; const d=new Date(value+(String(value).length===10?"T00:00:00":"")); return Number.isNaN(d.getTime())?value:d.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}); };
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),3200);}
function setStatus(id,msg,isError=false){const el=$(id);if(!el)return;el.textContent=msg;el.classList.toggle("error",isError);}
async function init(){
  if(!window.supabase){setStatus("connection-status","Supabase client could not load. Check your internet connection.",true);return;}
  supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
  setStatus("connection-status","Connected to IndoSpotters database");
  await Promise.all([loadAirports(),loadPhotos(),loadAircraftTypes(),loadRegistry()]);
  const {data:{session}}=await supabase.auth.getSession(); currentUser=session?.user||null; await updateAuthUI();
  supabase.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;setTimeout(()=>updateAuthUI(),0);});
}
async function loadAirports(){
  const {data,error}=await supabase.from("airports").select("icao,name,city,region,country").order("icao");
  if(error){console.error(error);setStatus("connection-status","Connected, but airport directory failed to load: "+error.message,true);return;}
  airports=data||[];renderAirports();$("airport-count").textContent=airports.length;
}
function renderAirports(){
  $("airport-grid").innerHTML=airports.length?airports.map(a=>`<article class="airport-card"><div class="airport-code">${escapeHtml(a.icao)}</div><div class="airport-name">${escapeHtml(a.name)}</div><div class="airport-city">${escapeHtml(a.city||"Indonesia")}</div><div class="airport-region">${escapeHtml(a.region||a.country||"Indonesia")}</div></article>`).join(""):'<div class="empty-state">Airport records are unavailable right now.</div>';
  const opts=airports.map(a=>`<option value="${escapeHtml(a.icao)}">${escapeHtml(a.icao)} — ${escapeHtml(a.name)}</option>`).join("");
  $("airport-filter").innerHTML='<option value="">All airports</option>'+opts;$("upload-airport").innerHTML='<option value="">Select airport</option>'+opts;
}
async function loadPhotos(){
  const {data,error}=await supabase.from("photos").select("id,registration,airline,aircraft_type,airport_code,caption,photographer_name,photo_date,livery,storage_path,created_at").eq("status","approved").order("created_at",{ascending:false}).limit(120);
  if(error){console.error(error);allPhotos=[];$("result-count").textContent="Could not load gallery";renderPhotos([]);return;}
  allPhotos=await Promise.all((data||[]).map(async p=>{let image_url="";if(p.storage_path){const {data:signed}=await supabase.storage.from("aircraft-photos").createSignedUrl(p.storage_path,3600);image_url=signed?.signedUrl||"";}return {...p,image_url};}));
  $("photo-count").textContent=allPhotos.length;searchPhotos();
}
async function loadAircraftTypes(){
  const {data,error}=await supabase.from("aircraft_types").select("type_code,manufacturer,model,category").order("manufacturer").order("model");
  if(error){console.error(error);$("type-grid").innerHTML='<div class="empty-state">Aircraft catalog could not load.</div>';return;}
  aircraftTypes=data||[];$("type-count").textContent=aircraftTypes.length;renderAircraftTypes();
  const opts=aircraftTypes.map(t=>`<option value="${escapeHtml(t.type_code)}">${escapeHtml(t.type_code)} · ${escapeHtml(t.manufacturer)} ${escapeHtml(t.model)}</option>`).join("");$("registry-type").innerHTML='<option value="">Select aircraft type (optional)</option>'+opts;const categories=[...new Set(aircraftTypes.map(t=>t.category).filter(Boolean))].sort();$("type-category").innerHTML='<option value="">All categories</option>'+categories.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");
}
function renderAircraftTypes(){const q=($("type-search")?.value||"").toLowerCase().trim(),cat=$("type-category")?.value||"";const rows=aircraftTypes.filter(t=>(!cat||t.category===cat)&&[t.type_code,t.manufacturer,t.model,t.category].some(v=>String(v||"").toLowerCase().includes(q)));$("type-grid").innerHTML=rows.length?rows.map(t=>`<article class="type-card"><span class="type-chip">${escapeHtml(t.category||"Aircraft")}</span><strong>${escapeHtml(t.manufacturer)} ${escapeHtml(t.model)}</strong><span class="type-code">${escapeHtml(t.type_code)}</span></article>`).join(""):'<div class="empty-state">No aircraft types match that search.</div>';$("type-result-count").textContent=`${rows.length} of ${aircraftTypes.length} aircraft types`;}
async function loadRegistry(){const {data,error}=await supabase.from("aircraft_registry").select("registration,operator,type_code,serial_number,notes,status,created_at").eq("status","approved").order("registration").limit(500);if(error){console.error(error);aircraftRegistry=[];}else aircraftRegistry=data||[];renderRegistry();$("registration-count").textContent=aircraftRegistry.length;}
function renderRegistry(){const q=($("registry-search")?.value||"").trim().toLowerCase();const rows=aircraftRegistry.filter(r=>[r.registration,r.operator,r.type_code,r.serial_number].some(v=>String(v||"").toLowerCase().includes(q)));$("registry-grid").innerHTML=rows.length?rows.map(r=>{const t=aircraftTypes.find(x=>x.type_code===r.type_code);return `<article class="registry-row"><div><strong>${escapeHtml(r.registration)}</strong><small>${escapeHtml(r.operator||"Operator not listed")}</small></div><div><span>${escapeHtml(t?`${t.manufacturer} ${t.model}`:r.type_code||"Type not listed")}</span><small>${escapeHtml(r.serial_number||"Serial number not listed")}</small></div></article>`}).join(""):'<div class="empty-state">No approved registrations yet. Search again or suggest a registration after signing in.</div>';$("registry-result-count").textContent=`${rows.length} registrations`;
}
function photoCard(p){const img=p.image_url?`<img loading="lazy" src="${escapeHtml(p.image_url)}" alt="${escapeHtml(p.registration+" "+p.aircraft_type)}">`:`<div class="placeholder-plane" aria-label="No preview image">✈</div>`;return `<article class="photo-card" tabindex="0" role="button" data-photo-id="${escapeHtml(p.id||p.registration)}"><div class="photo-thumb">${img}<span class="photo-tag">${escapeHtml(p.airport_code||"INDONESIA")}</span></div><div class="photo-info"><div class="photo-reg">${escapeHtml(p.registration||"Unknown registration")}</div><div class="photo-type">${escapeHtml(p.aircraft_type||"Aircraft type not supplied")}</div><div class="photo-meta"><span class="photo-airline">${escapeHtml(p.airline||"Unknown operator")}</span><span>${escapeHtml(formatDate(p.photo_date))}</span></div></div></article>`;}
function renderPhotos(photos){$("result-count").textContent=`${photos.length} ${photos.length===1?"photo":"photos"}`;$("gallery-grid").innerHTML=photos.length?photos.map(photoCard).join(""):'<div class="empty-state"><strong>No approved photos yet.</strong><br>Be one of the first Indonesian spotters to submit a photo.</div>';}
function searchPhotos(event){event?.preventDefault();const q=$("q").value.trim().toLowerCase(),airport=$("airport-filter").value,sort=$("sort-filter").value;let filtered=allPhotos.filter(p=>[p.registration,p.airline,p.aircraft_type,p.airport_code,p.livery,p.photographer_name].some(v=>String(v||"").toLowerCase().includes(q))&&(!airport||p.airport_code===airport));if(sort==="oldest")filtered.sort((a,b)=>String(a.photo_date||"").localeCompare(String(b.photo_date||"")));else if(sort==="registration")filtered.sort((a,b)=>String(a.registration||"").localeCompare(String(b.registration||"")));else filtered.sort((a,b)=>String(b.created_at||b.photo_date||"").localeCompare(String(a.created_at||a.photo_date||"")));renderPhotos(filtered);}
async function updateAuthUI(){const button=$("auth-button");button.textContent=currentUser?(currentUser.email?.split("@")[0]||"My account")+" · Sign out":"Sign in / Join";$("account-panel").classList.toggle("hidden",!currentUser);$("upload-status").textContent=currentUser?"Signed in. New uploads are reviewed before publication.":"Sign in to submit photos and aircraft records.";if(currentUser){const {data:profile}=await supabase.from("profiles").select("display_name,role").eq("id",currentUser.id).maybeSingle();$("profile-name").value=profile?.display_name||currentUser.user_metadata?.display_name||currentUser.email?.split("@")[0]||"";$("profile-email").textContent=currentUser.email||"";$("profile-role").textContent=profile?.role||"spotter";loadSubmissions();}else{$("my-submissions").innerHTML="";}}
async function handleAuthButton(){if(currentUser){const {error}=await supabase.auth.signOut();if(error)toast(error.message);else toast("Signed out.");}else{$("auth-dialog").showModal();}}
async function handleAuth(event){event.preventDefault();const email=$("auth-email").value.trim(),password=$("auth-password").value;setStatus("auth-status","Please wait…");const result=authMode==="signup"?await supabase.auth.signUp({email,password,options:{data:{display_name:$("auth-display-name").value.trim()}}}):await supabase.auth.signInWithPassword({email,password});if(result.error){setStatus("auth-status",result.error.message,true);return;}if(authMode==="signup"&&!result.data.session){setStatus("auth-status","Account created. Check your email to confirm it, then sign in.");return;}setStatus("auth-status",authMode==="signup"?"Account created!":"Signed in successfully.");setTimeout(()=>$("auth-dialog").close(),650);}
function toggleAuthMode(){authMode=authMode==="signin"?"signup":"signin";$("auth-title").textContent=authMode==="signup"?"Create your spotter account":"Welcome back";$("auth-submit").textContent=authMode==="signup"?"Create account":"Sign in";$("auth-toggle").textContent=authMode==="signup"?"Already registered? Sign in":"New to IndoSpotters? Create an account";$("signup-name-wrap").classList.toggle("hidden",authMode!=="signup");$("auth-password").autocomplete=authMode==="signup"?"new-password":"current-password";}
async function submitPhoto(event){event.preventDefault();if(!currentUser){$("auth-dialog").showModal();setStatus("upload-status","Please sign in before submitting.",true);return;}const file=$("photo-file").files[0];if(!file)return;if(file.size>12*1024*1024){setStatus("upload-status","Please choose an image smaller than 12 MB.",true);return;}if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setStatus("upload-status","Use a JPG, PNG, or WebP image.",true);return;}setStatus("upload-status","Uploading photo…");const ext=file.name.split(".").pop().toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",path=`${currentUser.id}/${crypto.randomUUID()}.${ext}`;const {error:storageError}=await supabase.storage.from("aircraft-photos").upload(path,file,{contentType:file.type,upsert:false});if(storageError){setStatus("upload-status","Upload failed: "+storageError.message,true);return;}const {error:dbError}=await supabase.from("photos").insert({user_id:currentUser.id,registration:$("registration").value.trim().toUpperCase(),airline:$("airline").value.trim(),aircraft_type:$("aircraft-type").value.trim(),airport_code:$("upload-airport").value,photo_date:$("photo-date").value||null,livery:$("livery").value.trim()||null,caption:$("caption").value.trim()||null,image_url:"",storage_path:path,status:"pending",photographer_name:$("profile-name").value.trim()||currentUser.email?.split("@")[0]||"Community spotter"});if(dbError){setStatus("upload-status","File uploaded, but details could not be saved: "+dbError.message,true);return;}setStatus("upload-status","Submitted! Your photo is waiting for moderator approval.");$("upload-form").reset();await loadSubmissions();toast("Photo submitted for review.");}
async function loadSubmissions(){if(!currentUser)return;const {data,error}=await supabase.from("photos").select("id,registration,aircraft_type,airport_code,status,created_at").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(50);if(error){$("my-submissions").innerHTML=`<p class="muted small">Could not load submissions: ${escapeHtml(error.message)}</p>`;return;}$("my-submissions").innerHTML=(data||[]).length?data.map(p=>`<div class="submission-item"><span><strong>${escapeHtml(p.registration)}</strong> · ${escapeHtml(p.aircraft_type)} · ${escapeHtml(p.airport_code)}</span><span class="status-pill ${escapeHtml(p.status)}">${escapeHtml(p.status)}</span></div>`).join(""):'<p class="muted small">No photo submissions yet.</p>';const {data:regs,error:regError}=await supabase.from("aircraft_registry").select("registration,operator,type_code,status").eq("submitted_by",currentUser.id).order("created_at",{ascending:false}).limit(50);$("my-registry").innerHTML=regError?`<p class="muted small">Could not load registration suggestions.</p>`:(regs||[]).length?regs.map(r=>`<div class="submission-item"><span><strong>${escapeHtml(r.registration)}</strong> · ${escapeHtml(r.operator||r.type_code||"Registration suggestion")}</span><span class="status-pill ${escapeHtml(r.status)}">${escapeHtml(r.status)}</span></div>`).join(""):'<p class="muted small">No registration suggestions yet.</p>'; }
async function saveProfile(event){event.preventDefault();if(!currentUser)return;const name=$("profile-name").value.trim();const {error}=await supabase.from("profiles").update({display_name:name}).eq("id",currentUser.id);if(error){setStatus("profile-status",error.message,true);return;}setStatus("profile-status","Profile saved.");toast("Profile updated.");}
async function submitRegistry(event){event.preventDefault();if(!currentUser){$("auth-dialog").showModal();setStatus("registry-status","Sign in before suggesting an aircraft registration.",true);return;}const reg=$("new-registration").value.trim().toUpperCase();setStatus("registry-status","Submitting suggestion…");const {error}=await supabase.from("aircraft_registry").insert({registration:reg,operator:$("registry-operator").value.trim()||null,type_code:$("registry-type").value||null,serial_number:$("registry-serial").value.trim()||null,notes:$("registry-notes").value.trim()||null,status:"pending",submitted_by:currentUser.id});if(error){setStatus("registry-status",error.code==="23505"?"That registration already exists or has already been suggested.":error.message,true);return;}setStatus("registry-status","Suggestion received. It will appear publicly after verification.");$("registry-form").reset();if(currentUser)await loadSubmissions();toast("Registration sent for review.");}
function openPhoto(id){const p=allPhotos.find(x=>String(x.id||x.registration)===String(id));if(!p)return;$("photo-detail").innerHTML=`${p.image_url?`<img src="${escapeHtml(p.image_url)}" alt="${escapeHtml(p.registration)}">`:""}<div class="detail-text"><p class="eyebrow">${escapeHtml(p.airport_code||"INDONESIA")} · ${escapeHtml(formatDate(p.photo_date))}</p><h2>${escapeHtml(p.registration||"Unknown registration")}</h2><p><strong>${escapeHtml(p.airline||"Unknown operator")}</strong> · ${escapeHtml(p.aircraft_type||"Aircraft type not supplied")}</p>${p.livery?`<p>Livery: ${escapeHtml(p.livery)}</p>`:""}${p.caption?`<p>${escapeHtml(p.caption)}</p>`:""}<p>Photographer: <strong>${escapeHtml(p.photographer_name||"Community spotter")}</strong></p></div>`;$("photo-dialog").showModal();}
document.addEventListener("DOMContentLoaded",()=>{init();$("search-form").addEventListener("submit",searchPhotos);$("q").addEventListener("input",searchPhotos);$("airport-filter").addEventListener("change",searchPhotos);$("sort-filter").addEventListener("change",searchPhotos);$("auth-button").addEventListener("click",handleAuthButton);$("auth-form").addEventListener("submit",handleAuth);$("auth-toggle").addEventListener("click",toggleAuthMode);$("close-auth").addEventListener("click",()=>$("auth-dialog").close());$("upload-form").addEventListener("submit",submitPhoto);$("refresh-submissions").addEventListener("click",loadSubmissions);$("close-photo").addEventListener("click",()=>$("photo-dialog").close());$("gallery-grid").addEventListener("click",e=>{const card=e.target.closest("[data-photo-id]");if(card)openPhoto(card.dataset.photoId);});$("gallery-grid").addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.matches("[data-photo-id]")){e.preventDefault();openPhoto(e.target.dataset.photoId);}});$("type-search").addEventListener("input",renderAircraftTypes);$("type-category").addEventListener("change",renderAircraftTypes);$("registry-search").addEventListener("input",renderRegistry);$("registry-form").addEventListener("submit",submitRegistry);$("profile-form").addEventListener("submit",saveProfile);$("auth-dialog").addEventListener("close",()=>{if(authMode!=="signin"){authMode="signin";toggleAuthMode();}});});
